version: "3.3"

services:
  web:
    container_name: ${APP_NAME}_web
    build:
      context: .
      dockerfile: .docker/nginx.Dockerfile
    ports:
     - 4200:80
    links:
      - app
    volumes:
      - ./:/var/www

  app:
    build:
      context: .
      dockerfile: .docker/fpm.Dockerfile
    container_name: ${APP_NAME}_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    container_name: ${APP_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 4201:80
    environment:
      MYSQL_ROOT_PASSWORD: secret
